# This formula is auto-generated by .github/workflows/update-formula.yml,
# which tracks the latest @anima-labs/cli release on the npm registry.
# Manual edits will be overwritten on the next release.
class Anima < Formula
  desc "Official CLI for the Anima platform — identity infrastructure for AI agents"
  homepage "https://useanima.sh"
  url "https://registry.npmjs.org/@anima-labs/cli/-/cli-0.6.5.tgz"
  sha256 "b7132350456e73486688b6e95bb02287c6e2453986bdfe4f7d90d10633d3e071"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anima --version")
  end
end
