# This formula is auto-generated by .github/workflows/update-formula.yml,
# which tracks the latest @anima-labs/cli release on the npm registry.
# Manual edits will be overwritten on the next release.
class Anima < Formula
  desc "Official CLI for the Anima platform — identity infrastructure for AI agents"
  homepage "https://useanima.sh"
  url "https://registry.npmjs.org/@anima-labs/cli/-/cli-0.6.8.tgz"
  sha256 "b732c38e07cc44b4d41ef0958d393e7879a41543b08616b6c64d036d8b640660"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anima --version")
  end
end
