# This formula is auto-generated by .github/workflows/update-formula.yml,
# which tracks the latest @anima-labs/cli release on the npm registry.
# Manual edits will be overwritten on the next release.
class Anima < Formula
  desc "Official CLI for the Anima platform — identity infrastructure for AI agents"
  homepage "https://useanima.sh"
  url "https://registry.npmjs.org/@anima-labs/cli/-/cli-0.9.0.tgz"
  sha256 "5af549254c2b4e7b773a86e01f88e4ef2c0e694d65d5fe42d2308ab5d25759f3"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anima --version")
  end
end
